/* 상품 상태 */
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('001', '판매중', 'PRODUCT_STATE', 'N', '1', '상품상태');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('002', '판매예정', 'PRODUCT_STATE', 'N', '2', '상품상태');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('003', '판매종료', 'PRODUCT_STATE', 'N', '3', '상품상태');

/* 상품 종류 */
/*
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('001', '신발', 'PRODUCT_TYPE', 'N', '1', '상품종류');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('002', '셔츠', 'PRODUCT_TYPE', 'N', '2', '상품종류');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('003', '바지', 'PRODUCT_TYPE', 'N', '3', '상품종류');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('004', '모자', 'PRODUCT_TYPE', 'N', '4', '상품종류');
*/
DELETE FROM CMMN_CODE WHERE CMN_TYPE = 'PRODUCT_TYPE';
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('', '전체', NULL, 'N', '0');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('100', '신발', NULL, 'N', '1');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('101', '운동화', '100', 'N', '1');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('102', '농구화', '100', 'N', '2');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('103', '축구화', '100', 'N', '3');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('200', '상의', NULL, 'N', '2');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('201', '맨투맨', '200', 'N', '1');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('202', '셔츠', '200', 'N', '2');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('203', '후드', '200', 'N', '3');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('300', '하의', NULL, 'N', '3');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('301', '반바지', '300', 'N', '1');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('302', '긴바지', '300', 'N', '2');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('400', '모자', NULL, 'N', '4');
INSERT INTO PRODUCT_TYPE(TYPE_CD, TYPE_NM, UP_CD, DEL_YN, SRT_ODR) VALUES('900', '기타', NULL, 'N', '9');

/* 상품 리뷰 구분 */
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('PR001', '일반 후기', 'REVIEW_TYPE', 'N', '1', '상품 리뷰 타입');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('PR002', '상품 사진 후기', 'REVIEW_TYPE', 'N', '2', '상품 리뷰 타입');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('PR003', '익명 후기', 'REVIEW_TYPE', 'N', '3', '상품 리뷰 타입');

/* 주문 상태 코드 */
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('OC', '주문 완료', 'PAYMENT_STATE', 'N', '1', '상품 주문 상태'); -- order complete
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('PS', '결제 대기', 'PAYMENT_STATE', 'N', '2', '상품 주문 상태'); -- payment stand
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('PC', '결제 완료', 'PAYMENT_STATE', 'N', '3', '상품 주문 상태'); -- payment complete
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('DS', '배송 대기', 'PAYMENT_STATE', 'N', '4', '상품 주문 상태'); -- deliver stand
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('DD', '배송 시작', 'PAYMENT_STATE', 'N', '5', '상품 주문 상태'); -- deliver doing
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('DC', '배송 완료', 'PAYMENT_STATE', 'N', '6', '상품 주문 상태'); -- deliver complete
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('BC', '구매 확정', 'PAYMENT_STATE', 'N', '7', '상품 주문 상태'); -- buy complete
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('RR', '환불 요청', 'PAYMENT_STATE', 'N', '8', '상품 주문 상태'); -- refund request
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('RC', '환불 완료', 'PAYMENT_STATE', 'N', '9', '상품 주문 상태'); -- refund complete
COMMIT;

/* 게시판 종류 */
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('NOTICE', '공지사항', 'BBS_TYPE', 'N', '1', '게시판 종류');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('FAQ', '자주 묻는 질문', 'BBS_TYPE', 'N', '2', '게시판 종류');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('PRODUCT_QNA', '상품 문의', 'BBS_TYPE', 'N', '3', '게시판 종류');

/* 게시글 작성 상태 */
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('10', '임시 작성', 'WRT_STATE', 'N', '1', '게시글 작성 상태');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('20', '작성 완료', 'WRT_STATE', 'N', '2', '게시글 작성 상태');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('30', '답변 대기', 'WRT_STATE', 'N', '3', '게시글 작성 상태');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('40', '답변 완료', 'WRT_STATE', 'N', '4', '게시글 작성 상태');

/* 메뉴 구분 */
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('NAV_MENU', '상단 메뉴', 'MENU_DIV', 'N', '1', '메뉴 구분');

/* 성별 */
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('M', '남성', 'SEX', 'N', '1', '성별');
INSERT INTO CMMN_CODE(CMN_CD, CMN_NM, CMN_TYPE, DEL_YN, SRT_ODR, CODE_DETAIL) VALUES('W', '여성', 'SEX', 'N', '2', '성별');

/* 공통 시퀀스 */
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'PM', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '상품번호(MST) 시퀀스 번호 추출', SYSDATE);	-- product mst
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'PL', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '상품번호(LIST) 시퀀스 번호 추출', SYSDATE); -- product list
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'PF', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '상품 이미지 파일 번호 시퀀스 번호 추출', SYSDATE);-- product file
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'PR', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '상품 리뷰 시퀀스 번호 추출', SYSDATE);	-- product review
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'CF', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '공통파일번호 시퀀스 번호 추출', SYSDATE);-- cmmn file
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'ON', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '주문번호 시퀀스 번호 추출', SYSDATE);	-- order no
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'PP', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '구매내역번호 시퀀스 번호 추출', SYSDATE); -- payment history
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'B', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '게시글 작성 시퀀스 번호 추출', SYSDATE); -- Board
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'CERT', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '인증번호 테이블 시퀀스 번호 추출', SYSDATE); -- Board
INSERT INTO CMMN_SEQ(SEQ_VAL, SEQ_TYPE, SEQ_LENGTH, SEQ_DTTM, DTTM_TYPE, DETAIL, SYS_CHG_DTTM)
		VALUES ('1', 'PB', 5, TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM', '장바구니 시퀀스 번호 추출', SYSDATE); -- Product Basket		
		
/* 공통 메뉴 */
-- 상단 메뉴
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('1', '상품조회', 0, '/shop/product/list', NULL, 1, '', 'NAV_MENU', 'productListComponent', 'product-list-form');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME, EXC_ROLE) VALUES('2', '공지사항', 0, '/shop/notice', NULL, 2, '', 'NAV_MENU', 'noticeComponent', 'notice-form', 'ROLE_ADMIN');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME, EXC_ROLE) VALUES('3', 'FAQ', 0, '/shop/faq', NULL, 3, '', 'NAV_MENU', 'faqComponent', 'faq-form', 'ROLE_ADMIN');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('4', '장바구니', 0, '/shop/basket', NULL, 4, 'ROLE_USER', 'NAV_MENU', 'basketComponent', 'basket-form');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('10', '상품관리', 0, '/shop/admin/product', NULL, 5, 'ROLE_ADMIN', 'NAV_MENU', 'adminProductComponent', 'admin-product-form');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('11', '주문관리', 0, '/shop/admin/order', NULL, 6, 'ROLE_ADMIN', 'NAV_MENU', 'adminOrderComponent', 'admin-order-form');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('12', '통계', 0, '/shop/admin/statistics', NULL, 7, 'ROLE_ADMIN', 'NAV_MENU', 'adminStatisticsComponent', 'admin-statistics-form');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('13', '게시글관리', 0, '/shop/admin/product/qna', NULL, 4, 'ROLE_ADMIN', 'NAV_MENU', 'adminBbsManageComponent', 'admin-bbs-manage-form');

-- 로그인 전
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('5', '로그인', 0, '/shop/login', NULL, 1, '', 'LOGIN_MENU', 'loginComponent', 'login-form');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('6', '회원가입', 0, '/shop/join', NULL, 2, '', 'LOGIN_MENU', 'joinComponent', 'join-form');

-- 로그인 후 (로그아웃 마이페이지 관리자)
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('7', '로그아웃', 0, '/shop/logout', NULL, 3, '', 'LOGOUT_MENU', 'logoutComponent', 'logout-form');
INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('8', '마이페이지', 0, '/shop/mypage', NULL, 4, 'ROLE_USER', 'LOGOUT_MENU', 'mypageComponent', 'mypage-form');
--INSERT INTO CMMN_MENU(MENU_ID, MENU_NAME, LVL, LOC, UP_ID, SRT_ODR, ROLE, MENU_DIV, COMPONENT, NAME) VALUES('9', '관리자', 0, '/shop/admin', NULL, 5, 'ROLE_ADMIN', 'LOGOUT_MENU', 'adminIndexComponent', 'admin-form');
