server:
 port: 8081

# slf4j Log Level 
logging:
  level:
    root: info
    com:
      shop:
        mall:
          repository: debug

# Oracle MyBatis
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #oracle.jdbc.OracleDriver
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe 
    #jdbc:oracle:thin:@localhost:1521/xe
    username: shop
    password: shop7
    
# File Upload 제한
  servlet:
    multipart:
      max-file-size: 10MB
  http: 
    multipart: 
      enabled: false

# File Upload Path
upload-file-path: static/images/
upload-path: src/main/webapp/
    